import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 翻译字典
const translations = {
  zh: {
    // Navigation
    'nav.dashboard': '仪表板',
    'nav.portfolio': '投资组合',
    'nav.trading': '交易',
    'nav.strategies': '策略管理',
    'nav.analysis': '分析',
    'nav.backtesting': '回测',
    'nav.monitoring': '监控',
    'nav.settings': '设置',
    
    // Common
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.create': '创建',
    'common.test': '测试',
    'common.validate': '验证',
    'common.confirm': '确认',
    'common.close': '关闭',
    
    // Strategy Editor
    'strategy.title': '策略管理',
    'strategy.subtitle': '创建和管理您的自定义交易策略',
    'strategy.page_description': '创建、编辑和管理您的交易策略',
    'strategy.list': '策略列表',
    'strategy.create': '新建策略',
    'strategy.templates': '策略模板',
    'strategy.name': '策略名称',
    'strategy.description': '描述',
    'strategy.author': '作者',
    'strategy.tags': '标签',
    'strategy.code': '策略代码',
    'strategy.parameters': '默认参数',
    'strategy.validate_code': '验证代码',
    'strategy.test_strategy': '测试策略',
    'strategy.code_valid': '代码验证通过',
    'strategy.code_invalid': '代码验证失败',
    'strategy.test_passed': '策略测试通过',
    'strategy.test_failed': '策略测试失败',
    'strategy.created': '策略创建成功',
    'strategy.updated': '策略更新成功',
    'strategy.deleted': '策略删除成功',
    'strategy.delete_confirm': '确定要删除这个策略吗？此操作不可撤销。',
    'strategy.no_strategies': '暂无自定义策略',
    'strategy.welcome_title': '策略编辑器',
    'strategy.welcome_subtitle': '创建和管理您的自定义交易策略。选择一个策略查看详情，或创建新的策略。',
    'strategy.create_new': '创建新策略',
    'strategy.from_template': '从模板开始',
    'strategy.creating': '创建新策略',
    'strategy.editing': '编辑策略',
    'strategy.version': '版本',
    'strategy.created_at': '创建时间',
    'strategy.updated_at': '更新时间',
    'strategy.code_display': '策略代码',
    'strategy.default_params': '默认参数',
    
    // Backtesting
    'backtest.title': '回测 & 自动交易',
    'backtest.subtitle': '测试交易策略并管理自动交易',
    'backtest.config': '回测配置',
    'backtest.symbol': '交易对',
    'backtest.period': '回测周期（天）',
    'backtest.initial_capital': '初始资金（USDT）',
    'backtest.strategy': '交易策略',
    'backtest.strategy_loading': '加载策略中...',
    'backtest.builtin_strategies': '内置策略',
    'backtest.custom_strategies': '自定义策略',
    'backtest.risk_params': '风险参数',
    'backtest.max_position': '最大仓位（%）',
    'backtest.stop_loss': '止损（%）',
    'backtest.take_profit': '止盈（%）',
    'backtest.run': '运行回测',
    'backtest.running': '运行回测中...',
    'backtest.auto_trading': '自动交易状态',
    'backtest.enable_auto': '启用自动交易',
    'backtest.disable_auto': '禁用自动交易',
    'backtest.status': '状态',
    'backtest.last_signal': '最后信号',
    'backtest.todays_pnl': '今日盈亏',
    'backtest.performance': '性能指标',
    'backtest.total_return': '总收益',
    'backtest.sharpe_ratio': '夏普比率',
    'backtest.max_drawdown': '最大回撤',
    'backtest.win_rate': '胜率',
    'backtest.total_trades': '总交易数',
    'backtest.final_capital': '最终资金',
    'backtest.profit_factor': '盈利因子',
    'backtest.volatility': '波动率',
    'backtest.equity_curve': '资产曲线',
    'backtest.drawdown_curve': '回撤曲线',
    
    // Settings
    'settings.title': '系统设置',
    'settings.subtitle': '配置和管理您的比特币交易系统',
    'settings.system_control': '系统控制',
    'settings.manual_trading': '手动交易',
    'settings.config': '参数配置',
    'settings.alerts': '告警管理',
    'settings.system_status': '系统状态',
    'settings.system_ops': '系统操作',
    'settings.start': '启动',
    'settings.stop': '停止',
    'settings.restart': '重启',
    'settings.component_health': '组件健康状态',
    'settings.total_components': '总组件数',
    'settings.healthy': '健康',
    'settings.unhealthy': '异常',
    'settings.websocket': 'WebSocket连接',
    'settings.connection_status': '连接状态',
    'settings.connected': '已连接',
    'settings.connecting': '连接中',
    'settings.connection_error': '连接错误',
    'settings.disconnected': '未连接',
    'settings.connect': '连接',
    'settings.disconnect': '断开',
    'settings.connection_stats': '连接统计',
    'settings.message_count': '接收消息数',
    'settings.last_message': '最后消息时间',
    
    // Dashboard
    'dashboard.title': '仪表板',
    'dashboard.subtitle': '比特币交易系统概览',
    
    // Portfolio
    'portfolio.title': '投资组合',
    'portfolio.subtitle': '查看您的投资组合表现',
    
    // Trading
    'trading.title': '交易',
    'trading.subtitle': '下单和管理您的交易',
    'trading.place_order': '下单',
    'trading.order_history': '订单历史',
    'trading.auto_trading': '自动交易',
    'trading.enable_auto': '启用自动交易',
    'trading.disable_auto': '禁用自动交易',
    'trading.symbol': '交易对',
    'trading.side': '方向',
    'trading.buy': '买入',
    'trading.sell': '卖出',
    'trading.order_type': '订单类型',
    'trading.market': '市价',
    'trading.limit': '限价',
    'trading.quantity': '数量',
    'trading.price': '价格',
    'trading.current_price': '当前价格',
    'trading.placing_order': '下单中...',
    'trading.order_id': '订单ID',
    'trading.status': '状态',
    'trading.created': '创建时间',
    'trading.actions': '操作',
    'trading.cancel': '取消',
    'trading.strategy': '策略',
    'trading.last_signal': '最后信号',
    'trading.todays_trades': '今日交易',
    'trading.no_orders': '暂无订单',
    'trading.loading_orders': '加载订单中...',
    'trading.valid_quantity': '请输入有效数量',
    'trading.valid_price': '请输入有效价格',
    'trading.order_placed': '订单已提交',
    'trading.order_cancelled': '订单已取消',
    
    // Analysis
    'analysis.title': '分析',
    'analysis.subtitle': '市场情绪和技术分析与实时图表',
    'analysis.trigger_analysis': '触发分析',
    'analysis.analyzing': '分析中...',
    'analysis.sentiment_summary': '情绪分析摘要',
    'analysis.technical_summary': '技术分析摘要',
    'analysis.trading_decision': '交易决策',
    'analysis.sentiment_score': '情绪评分',
    'analysis.confidence': '置信度',
    'analysis.key_topics': '关键话题',
    'analysis.signal_strength': '信号强度',
    'analysis.key_indicators': '关键指标',
    'analysis.action': '操作',
    'analysis.quantity': '数量',
    'analysis.reasoning': '推理',
    'analysis.last_updated': '最后更新',
    'analysis.no_data': '暂无数据',
    'analysis.very_bullish': '非常看涨',
    'analysis.bullish': '看涨',
    'analysis.neutral': '中性',
    'analysis.bearish': '看跌',
    'analysis.very_bearish': '非常看跌',
    
    // Monitoring
    'monitoring.title': '监控',
    'monitoring.subtitle': '实时系统健康和性能指标',
    'monitoring.refresh': '刷新',
    'monitoring.system_health': '系统健康',
    'monitoring.system_resources': '系统资源',
    'monitoring.application_metrics': '应用指标',
    'monitoring.trading_metrics': '交易指标',
    'monitoring.system_alerts': '系统告警',
    'monitoring.cpu_usage': 'CPU使用率',
    'monitoring.memory_usage': '内存使用率',
    'monitoring.disk_usage': '磁盘使用率',
    'monitoring.uptime': '运行时间',
    'monitoring.total_requests': '总请求数',
    'monitoring.requests_per_min': '每分钟请求',
    'monitoring.error_rate': '错误率',
    'monitoring.avg_response': '平均响应时间',
    'monitoring.active_connections': '活跃连接',
    'monitoring.market_updates': '市场更新',
    'monitoring.cache_hit_rate': '缓存命中率',
    'monitoring.api_calls_today': '今日API调用',
    'monitoring.last_price_update': '最后价格更新',
    'monitoring.no_alerts': '无系统告警',
    'monitoring.loading_data': '加载监控数据中...',
    'monitoring.component': '组件',
    'monitoring.resolved': '已解决',
    'monitoring.active': '活跃',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.portfolio': 'Portfolio',
    'nav.trading': 'Trading',
    'nav.strategies': 'Strategies',
    'nav.analysis': 'Analysis',
    'nav.backtesting': 'Backtesting',
    'nav.monitoring': 'Monitoring',
    'nav.settings': 'Settings',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.test': 'Test',
    'common.validate': 'Validate',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    
    // Strategy Editor
    'strategy.title': 'Strategy Management',
    'strategy.subtitle': 'Create and manage your custom trading strategies',
    'strategy.page_description': 'Create, edit and manage your trading strategies',
    'strategy.list': 'Strategy List',
    'strategy.create': 'New Strategy',
    'strategy.templates': 'Strategy Templates',
    'strategy.name': 'Strategy Name',
    'strategy.description': 'Description',
    'strategy.author': 'Author',
    'strategy.tags': 'Tags',
    'strategy.code': 'Strategy Code',
    'strategy.parameters': 'Default Parameters',
    'strategy.validate_code': 'Validate Code',
    'strategy.test_strategy': 'Test Strategy',
    'strategy.code_valid': '✅ Code validation passed',
    'strategy.code_invalid': '❌ Code validation failed',
    'strategy.test_passed': 'Strategy test passed',
    'strategy.test_failed': 'Strategy test failed',
    'strategy.created': 'Strategy created successfully',
    'strategy.updated': 'Strategy updated successfully',
    'strategy.deleted': 'Strategy deleted successfully',
    'strategy.delete_confirm': 'Are you sure you want to delete this strategy? This action cannot be undone.',
    'strategy.no_strategies': 'No custom strategies yet',
    'strategy.welcome_title': 'Strategy Editor',
    'strategy.welcome_subtitle': 'Create and manage your custom trading strategies. Select a strategy to view details, or create a new one.',
    'strategy.create_new': 'Create New Strategy',
    'strategy.from_template': 'Start from Template',
    'strategy.creating': 'Creating New Strategy',
    'strategy.editing': 'Editing Strategy',
    'strategy.version': 'Version',
    'strategy.created_at': 'Created At',
    'strategy.updated_at': 'Updated At',
    'strategy.code_display': 'Strategy Code',
    'strategy.default_params': 'Default Parameters',
    
    // Backtesting
    'backtest.title': 'Backtesting & Auto Trading',
    'backtest.subtitle': 'Test trading strategies and manage automated trading',
    'backtest.config': 'Backtest Configuration',
    'backtest.symbol': 'Symbol',
    'backtest.period': 'Backtest Period (Days)',
    'backtest.initial_capital': 'Initial Capital (USDT)',
    'backtest.strategy': 'Trading Strategy',
    'backtest.strategy_loading': 'Loading strategies...',
    'backtest.builtin_strategies': 'Built-in Strategies',
    'backtest.custom_strategies': 'Custom Strategies',
    'backtest.risk_params': 'Risk Parameters',
    'backtest.max_position': 'Max Position Size (%)',
    'backtest.stop_loss': 'Stop Loss (%)',
    'backtest.take_profit': 'Take Profit (%)',
    'backtest.run': 'Run Backtest',
    'backtest.running': 'Running backtest...',
    'backtest.auto_trading': 'Auto Trading Status',
    'backtest.enable_auto': 'Enable Auto Trading',
    'backtest.disable_auto': 'Disable Auto Trading',
    'backtest.status': 'Status',
    'backtest.last_signal': 'Last Signal',
    'backtest.todays_pnl': "Today's P&L",
    'backtest.performance': 'Performance Metrics',
    'backtest.total_return': 'Total Return',
    'backtest.sharpe_ratio': 'Sharpe Ratio',
    'backtest.max_drawdown': 'Max Drawdown',
    'backtest.win_rate': 'Win Rate',
    'backtest.total_trades': 'Total Trades',
    'backtest.final_capital': 'Final Capital',
    'backtest.profit_factor': 'Profit Factor',
    'backtest.volatility': 'Volatility',
    'backtest.equity_curve': 'Equity Curve',
    'backtest.drawdown_curve': 'Drawdown Curve',
    
    // Settings
    'settings.title': 'System Settings',
    'settings.subtitle': 'Configure and manage your Bitcoin trading system',
    'settings.system_control': 'System Control',
    'settings.manual_trading': 'Manual Trading',
    'settings.config': 'Configuration',
    'settings.alerts': 'Alert Management',
    'settings.system_status': 'System Status',
    'settings.system_ops': 'System Operations',
    'settings.start': 'Start',
    'settings.stop': 'Stop',
    'settings.restart': 'Restart',
    'settings.component_health': 'Component Health',
    'settings.total_components': 'Total Components',
    'settings.healthy': 'Healthy',
    'settings.unhealthy': 'Unhealthy',
    'settings.websocket': 'WebSocket Connection',
    'settings.connection_status': 'Connection Status',
    'settings.connected': 'Connected',
    'settings.connecting': 'Connecting...',
    'settings.connection_error': 'Connection Error',
    'settings.disconnected': 'Disconnected',
    'settings.connect': 'Connect',
    'settings.disconnect': 'Disconnect',
    'settings.connection_stats': 'Connection Stats',
    'settings.message_count': 'Messages Received',
    'settings.last_message': 'Last Message Time',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Bitcoin Trading System Overview',
    
    // Portfolio
    'portfolio.title': 'Portfolio',
    'portfolio.subtitle': 'View your portfolio performance',
    
    // Trading
    'trading.title': 'Trading',
    'trading.subtitle': 'Place orders and manage your trades',
    'trading.place_order': 'Place Order',
    'trading.order_history': 'Order History',
    'trading.auto_trading': 'Auto Trading',
    'trading.enable_auto': 'Enable Auto Trading',
    'trading.disable_auto': 'Disable Auto Trading',
    'trading.symbol': 'Symbol',
    'trading.side': 'Side',
    'trading.buy': 'Buy',
    'trading.sell': 'Sell',
    'trading.order_type': 'Order Type',
    'trading.market': 'Market',
    'trading.limit': 'Limit',
    'trading.quantity': 'Quantity',
    'trading.price': 'Price',
    'trading.current_price': 'Current Price',
    'trading.placing_order': 'Placing Order...',
    'trading.order_id': 'Order ID',
    'trading.status': 'Status',
    'trading.created': 'Created',
    'trading.actions': 'Actions',
    'trading.cancel': 'Cancel',
    'trading.strategy': 'Strategy',
    'trading.last_signal': 'Last Signal',
    'trading.todays_trades': "Today's Trades",
    'trading.no_orders': 'No orders found',
    'trading.loading_orders': 'Loading orders...',
    'trading.valid_quantity': 'Please enter a valid quantity',
    'trading.valid_price': 'Please enter a valid price for limit orders',
    'trading.order_placed': 'Order placed successfully',
    'trading.order_cancelled': 'Order cancelled successfully',
    
    // Analysis
    'analysis.title': 'Analysis',
    'analysis.subtitle': 'Market sentiment and technical analysis with real-time charts',
    'analysis.trigger_analysis': 'Trigger Analysis',
    'analysis.analyzing': 'Analyzing...',
    'analysis.sentiment_summary': 'Sentiment Analysis Summary',
    'analysis.technical_summary': 'Technical Analysis Summary',
    'analysis.trading_decision': 'Trading Decision',
    'analysis.sentiment_score': 'Sentiment Score',
    'analysis.confidence': 'Confidence',
    'analysis.key_topics': 'Key Topics',
    'analysis.signal_strength': 'Signal Strength',
    'analysis.key_indicators': 'Key Indicators',
    'analysis.action': 'Action',
    'analysis.quantity': 'Quantity',
    'analysis.reasoning': 'Reasoning',
    'analysis.last_updated': 'Last updated',
    'analysis.no_data': 'No analysis data available',
    'analysis.very_bullish': 'Very Bullish',
    'analysis.bullish': 'Bullish',
    'analysis.neutral': 'Neutral',
    'analysis.bearish': 'Bearish',
    'analysis.very_bearish': 'Very Bearish',
    
    // Monitoring
    'monitoring.title': 'Monitoring',
    'monitoring.subtitle': 'Real-time system health and performance metrics',
    'monitoring.refresh': 'Refresh',
    'monitoring.system_health': 'System Health',
    'monitoring.system_resources': 'System Resources',
    'monitoring.application_metrics': 'Application Metrics',
    'monitoring.trading_metrics': 'Trading Metrics',
    'monitoring.system_alerts': 'System Alerts',
    'monitoring.cpu_usage': 'CPU Usage',
    'monitoring.memory_usage': 'Memory Usage',
    'monitoring.disk_usage': 'Disk Usage',
    'monitoring.uptime': 'Uptime',
    'monitoring.total_requests': 'Total Requests',
    'monitoring.requests_per_min': 'Requests/min',
    'monitoring.error_rate': 'Error Rate',
    'monitoring.avg_response': 'Avg Response',
    'monitoring.active_connections': 'Active Connections',
    'monitoring.market_updates': 'Market Updates',
    'monitoring.cache_hit_rate': 'Cache Hit Rate',
    'monitoring.api_calls_today': 'API Calls Today',
    'monitoring.last_price_update': 'Last Price Update',
    'monitoring.no_alerts': 'No system alerts',
    'monitoring.loading_data': 'Loading monitoring data...',
    'monitoring.component': 'Component',
    'monitoring.resolved': 'Resolved',
    'monitoring.active': 'Active',
    
    // Language
    'language.switch': 'Switch Language',
    'language.chinese': '中文',
    'language.english': 'English',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // 从localStorage获取保存的语言设置，默认为中文
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'zh';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};